export const FETCH_TODOS_REQUESTED = "FETCH_TODOS_REQUESTED";
export const FETCH_TODOS_SUCCESS = "FETCH_TODOS_SUCCESS";
export const FETCH_TODOS_ERROR = "FETCH_TODOS_ERROR";

export const ADD_TODO_REQUESTED = "ADD_TODO_REQUESTED";
export const ADD_TODO_SUCCESS = "ADD_TODO_SUCCESS";
export const ADD_TODO_ERROR = "ADD_TODO_ERROR";

export const DELETE_TODO_REQUESTED = "DELETE_TODO_REQUESTED";
export const DELETE_TODO_SUCCESS = "DELETE_TODO_SUCCESS";
export const DELETE_TODO_ERROR = "DELETE_TODO_ERROR";
