export const ADD_EXPANSE_REQUESTED = "ADD_EXPANSE_REQUESTED";
export const ADD_EXPANSE_SUCCESS = "ADD_EXPANSE_SUCCESS";
export const ADD_EXPANSE_ERROR = "ADD_EXPANSE_ERROR";

export const GET_EXPANSE_REQUESTED = "GET_EXPANSE_REQUESTED";
export const GET_EXPANSE_SUCCESS = "GET_EXPANSE_SUCCESS";
export const GET_EXPANSE_ERROR = "GET_EXPANSE_ERROR";
